#
# JBZoo - Toolbox
#
# This file is part of the JBZoo project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Toolbox
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Toolbox
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '45 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        composer_flags: [ "--prefer-lowest", "" ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üß™ PHPUnit Tests
        continue-on-error: ${{ matrix.experimental }}
        run: make test --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit - ${{ matrix.php-version }} - ${{ matrix.coverage }}
          path: build/


  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ast
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üëç Code Quality
        continue-on-error: ${{ matrix.experimental }}
        run: make codestyle --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linters - ${{ matrix.php-version }}
          path: build/


  report:
    name: Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üìù Build Reports
        continue-on-error: ${{ matrix.experimental }}
        run: make report-all --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports - ${{ matrix.php-version }}
          path: build/
